name: Build and Publish Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image Version'
        required: false
        default: 'latest'

jobs:
  build-and-push:
    permissions:
        packages: write
        contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Build and Publish Docker Image
        uses: TBXark/docker-action@v1.0.0      
        with:
          docker_registry: ghcr.io
          # To use the repository owner's username, use 'github.repository_owner' instead of 'github.actor'.
          docker_username: ${{ github.repository_owner }}
          docker_password: ${{ secrets.GITHUB_TOKEN }}
          backup_registry: ${{ secrets.BACKUP_REGISTRY }}
          backup_username: ${{ secrets.BACKUP_USERNAME }}
          backup_password: ${{ secrets.BACKUP_PASSWORD }}
